/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IOSQuickAccessIcons {
  IOSQuickAccessIcons._();

  static const _kFontFam = 'IOSQA';

  static const IconData fachschaftlogo = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hslogo = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData lsflogo = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData moodlelogo = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData webmailerlogo = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData award = IconData(0xe806, fontFamily: _kFontFam);

}
