/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
/// USAGE Example:
/// import 'package:MyStudyBuddy2/theme/ios_quick_access_icons.dart';
/// Button(child: Icon(IOSQuickAccessIcons.award)
///
///
///
///
/// ##############################
/// #########IMPORTANT:###########
/// ##############################
/// All these icons (except fachschaftlogo, hslogo, lsflogo, moodlelogo,
/// webmailerlogo) are under Apple Inc.'s Copyright and may only be used
/// in accordance to the LICENSE AGREEMENT FOR THE APPLE SAN FRANCISCO FONT
/// 
import 'package:flutter/widgets.dart';

class IOSQuickAccessIcons {
  IOSQuickAccessIcons._();

  static const _kFontFam = 'IOSQA';
  static const IconData fachschaftlogo = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hslogo = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData lsflogo = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData moodlelogo = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData webmailerlogo = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData arrow_2_circlepath = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData f_cursive_circle = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cloud_sun_fill = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData envelope_fill = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData questionmark_circle = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData info_circle_fill = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData list_bullet_below_rectangle = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData list_bullet = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lock_open = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData lock_shield_fill = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData map_fill = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData pencil_circle_fill = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData person_circle = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData person = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData plus_circle = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData questionmark_circle_fill = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData rosette = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData smiley_fill = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData speedometer = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData square_and_arrow_down = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData studentdesk = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData book_fill = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData checkmark_square_fill = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData f_cursive_circle_fill = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData info_circle = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData chevron_left_slash_chevron_right = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData cloud = IconData(0xe823, fontFamily: _kFontFam);
}
