name: MyStudyBuddy2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter # https://https://flutter.dev/ *** BSD ***
  webview_flutter: ^0.3.19+7 # https://pub.dev/packages/webview_flutter *** BSD ***
  http: ^0.12.0+4 # https://pub.dev/packages/http *** BSD ***
  flutter_staggered_grid_view: ^0.3.0 # https://pub.dev/packages/flutter_staggered_grid_view *** MIT ***
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2 # https://pub.dev/packages/cupertino_icons *** MIT ***
  flutter_plugin_pdf_viewer: ^1.0.7 # https://pub.dev/packages/flutter_plugin_pdf_viewer *** BSD ***
  flutter_mailer: ^0.4.1+1 # https://pub.dev/packages/flutter_mailer *** MIT ***
  validators: ^2.0.0 # https://pub.dev/packages/validators *** MIT ***
  url_launcher: ^5.4.1 # https://pub.dev/packages/url_launcher *** BSD ***

  provider: ^4.0.4 # https://pub.dev/packages/provider *** MIT ***
  photo_view: ^0.9.2 #https://pub.dev/packages/photo_view *** MIT ***
  percent_indicator: ^2.1.1 #https://pub.dev/packages/percent_indicator *** BSD ***
  flutter_launcher_icons: ^0.7.4 #https://pub.dev/packages/flutter_launcher_icons *** MIT ***
  smooth_star_rating: 1.0.4+2 #https://pub.dev/packages/smooth_star_rating *** MIT ***

flutter_icons:
  android: "launcher_icon" # https://pub.dev/packages/flutter_launcher_icons *** MIT ***
  ios: true
  image_path: "assets/icons/app_icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
   
  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/
      - assets/icons/app_icon/
  #   - images/a_dot_ham.jpeg
      - assets/icons/QSP/Software_Icon.png
      - assets/icons/QSP/Medieninformatik_Icon.png
      - assets/icons/QSP/Cloud_Icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        # - asset: fonts/Roboto-Black.ttf
        # - asset: fonts/Roboto-BlackItalic.ttf
        # - asset: fonts/Roboto-Bold.ttf
        # - asset: fonts/Roboto-BoldItalic.ttf
        # - asset: fonts/Roboto-Italic.ttf
        # - asset: fonts/Roboto-Light.ttf
        # - asset: fonts/Roboto-LightItalic.ttf
        # - asset: fonts/Roboto-Medium.ttf
        # - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        # - asset: fonts/Roboto-Thin.ttf
        # - asset: fonts/Roboto-ThinItalic.ttf
    - family: Roboto Light  
      fonts:
        - asset: fonts/Roboto-Light.ttf

    - family:  QSPInfoIcons
      fonts:
        - asset: fonts/QSPInfoIcons.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
