/// Flutter icons QSPInfoIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QSPInfoIcons
///      fonts:
///       - asset: fonts/QSPInfoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QSPInfoIcons {
  QSPInfoIcons._();

  static const _kFontFam = 'QSPInfoIcons';

  static const IconData cloud_icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData medieninformatik_icon = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData software_icon = const IconData(0xe802, fontFamily: _kFontFam);
}
